require 'pry'
require 'Nokogiri'
require 'open-uri'
require_relative './nfl_top_stories/concerns/headline_choice'
require_relative './nfl_top_stories/version'
require_relative './nfl_top_stories/story'
require_relative './nfl_top_stories/headline'
require_relative './nfl_top_stories/cli'
